version: '2.3'

services:
  nlp: &nlp
    build:
      context: ./src
      dockerfile: '../Dockerfile-mac'
    image: sdbert
    volumes:
    - ./src:/app
    - ./data:/app/data
    - ./lm_models:/app/lm_models
    - ./tokcl_models:/app/tokcl_models
    env_file:
    - ./.env
    ipc: host
    tty: true
    stdin_open: true
    working_dir: /app

  tensorboard:
    build:
      context: ./src
      dockerfile: '../Dockerfile-mac'
    depends_on:
    - nlp
    ports:
    - 6007:6007
    volumes:
    - ./runs:/runs
    command: tensorboard --logdir /runs --port 6007 --bind_all

  celery:
    build:
      context: ./src
      dockerfile: '../Dockerfile-mac'
    depends_on:
    - rabbitmq
    volumes:
    - ./src:/app
    working_dir: /app
    command: celery -A "lm" worker --loglevel=info

  flower:
    <<: *nlp
    depends_on:
    - celery
    ports:
      - "5555:5555"
    command: flower -A "lm" --port=5555 --broker="rabbitmq"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      # The standard AMQP protocol port
      - '5672:5672'
      # HTTP management UI at http://localhost:15672/
      - '15672:15672'
