# nvidia-docker run --shm-size 8G --rm -it -v /raid/lemberge/vsearch:/workspace/vsearch -p12345:6005 -v /tmp/.X11-unix:/tmp/.X11-unix -e DISPLAY -e XAUTHORITY -e NVIDIA_DRIVER_CAPABILITIES=all tl/vsearch:last
version: '2.3'

services:
  lm:
    build:
      context: .
      dockerfile: './Dockerfile'
    image: sdbert
    runtime: nvidia
    volumes:
    - .:/app
    env_file:
    - ./.env
    ipc: host
    tty: true
    stdin_open: true
    working_dir: /app
    # command: python -c "import nltk; nltk.download('averaged_perceptron_tagger')"

  tensorboard:
    build:
      context: .
      dockerfile: './Dockerfile'
    depends_on:
    - lm
    runtime: nvidia
    ports:
    - 6007:6007
    volumes:
    - ./runs:/runs
    command: tensorboard --logdir /runs --port 6007 --bind_all
