version: '2.3'

services:
  nlp:
    build:
      context: .
      dockerfile: './Dockerfile'
    image: sdbert
    runtime: nvidia
    volumes:
    - .:/app
    env_file:
    - ./.env
    ipc: host
    tty: true
    stdin_open: true
    working_dir: /app
    # command: python -c "import nltk; nltk.download('averaged_perceptron_tagger')"

  tensorboard:
    build:
      context: .
      dockerfile: './Dockerfile'
    depends_on:
    - nlp
    runtime: nvidia
    ports:
    - 6007:6007
    volumes:
    - ./runs:/runs
    command: tensorboard --logdir /runs --port 6007 --bind_all
